/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejerciciosSemana09.ejercicio02;

import java.util.ArrayList;

/**
 *
 * @author COREI5 8VA
 */
public class Ejercicio02 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio02.class.getName());

    private ArrayList<Producto> listaProductos = new ArrayList<>();
    private ArrayList<MateriaPrima> listaMateriasPrimas = new ArrayList<>();
    private ArrayList<DetalleDeProducto> listaDetalles = new ArrayList<>();

    private int idProductoActual = 1;
    private int idMateriaPrimaActual = 1;

    /**
     * Creates new form Ejercicio02
     */
    public Ejercicio02() {
        setSize(1100, 1000);
        initComponents();
        inicializarTablaDetalles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void actualizarComboProductos() {
        cboProductos.removeAllItems();
        for (Producto p : listaProductos) {
            cboProductos.addItem(p.getIdProducto() + " - " + p.getNombre());
        }
    }

    private void actualizarComboMateriasPrimas() {
        cboMateriaPrima.removeAllItems();
        for (MateriaPrima m : listaMateriasPrimas) {
            cboMateriaPrima.addItem(m.getIdMateriaPrima() + " - " + m.getNombre());
        }
    }

    private void inicializarTablaDetalles() {
        String[] columnas = {"Producto", "Materia Prima", "Cantidad usada"};
        Object[][] data = new Object[0][3];  // sin filas al inicio
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
    }

    private void actualizarTablaDetalles() {
        String[] columnas = {"Producto", "Materia Prima", "Cantidad usada"};
        Object[][] data = new Object[listaDetalles.size()][3];

        for (int i = 0; i < listaDetalles.size(); i++) {
            DetalleDeProducto d = listaDetalles.get(i);
            data[i][0] = d.getProducto().getNombre();
            data[i][1] = d.getMateriaPrima().getNombre();
            data[i][2] = d.getCantidadUsada();
        }

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistrarProducto = new javax.swing.JLabel();
        lblCostoFabricacion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCnatidadFabricada = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidadFabricada = new javax.swing.JTextField();
        txtCostoFabricacion = new javax.swing.JTextField();
        btnGuardarProducto = new javax.swing.JButton();
        lblidProducto = new javax.swing.JLabel();
        lblProductoId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRegistrarMateriaPrima = new javax.swing.JLabel();
        lblIdMateriaPrima = new javax.swing.JLabel();
        txtNombreMateriaPrima = new javax.swing.JTextField();
        btnGuardarMateriaPrima = new javax.swing.JButton();
        lblNombreMateriaPrima = new javax.swing.JLabel();
        lblMateriaPrimaID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblDetaleProducto = new javax.swing.JLabel();
        lblProductoDetalle = new javax.swing.JLabel();
        lblMateriaPrimaDetalle = new javax.swing.JLabel();
        lblCantidadUsada = new javax.swing.JLabel();
        txtCantidadUsada = new javax.swing.JTextField();
        cboMateriaPrima = new javax.swing.JComboBox<>();
        cboProductos = new javax.swing.JComboBox<>();
        btnGuardarDetalle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistrarProducto.setText("Registrar Producto");
        jPanel1.add(lblRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, -1, -1));

        lblCostoFabricacion.setText("Costo de Fabricación");
        jPanel1.add(lblCostoFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblCnatidadFabricada.setText("Cantidad Fabricada");
        jPanel1.add(lblCnatidadFabricada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 180, 30));
        jPanel1.add(txtCantidadFabricada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 30));
        jPanel1.add(txtCostoFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 30));

        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, -1));

        lblidProducto.setText("ID");
        jPanel1.add(lblidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblProductoId.setText("1");
        jPanel1.add(lblProductoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 310));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarMateriaPrima.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistrarMateriaPrima.setText("Registrar Materia Prima");
        jPanel2.add(lblRegistrarMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblIdMateriaPrima.setText("ID:");
        jPanel2.add(lblIdMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel2.add(txtNombreMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 30));

        btnGuardarMateriaPrima.setText("Guardar");
        btnGuardarMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateriaPrimaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        lblNombreMateriaPrima.setText("Nombre");
        jPanel2.add(lblNombreMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblMateriaPrimaID.setText("1");
        jPanel2.add(lblMateriaPrimaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 180));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 330, 200));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 370, 200));

        lblDetaleProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDetaleProducto.setText("Detalle de Producto");
        jPanel3.add(lblDetaleProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblProductoDetalle.setText("Producto");
        jPanel3.add(lblProductoDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblMateriaPrimaDetalle.setText("Materia Prima");
        jPanel3.add(lblMateriaPrimaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblCantidadUsada.setText("Cantidad usada");
        jPanel3.add(lblCantidadUsada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel3.add(txtCantidadUsada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 230, 30));

        cboMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel3.add(cboMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, 30));

        cboProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel3.add(cboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 230, 30));

        btnGuardarDetalle.setText("Guardar");
        btnGuardarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDetalleActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 80, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 500));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDetalle);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        try {
            String nombre = txtNombreProducto.getText();
            int cantidad = Integer.parseInt(txtCantidadFabricada.getText());
            double costo = Double.parseDouble(txtCostoFabricacion.getText());

            Producto p = new Producto(idProductoActual, nombre, cantidad, costo);
            listaProductos.add(p);

            idProductoActual++;
            lblProductoId.setText(String.valueOf(idProductoActual));

            txtNombreProducto.setText("");
            txtCantidadFabricada.setText("");
            txtCostoFabricacion.setText("");

            actualizarComboProductos();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa datos válidos.");
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnGuardarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDetalleActionPerformed
        if (cboProductos.getSelectedIndex() == -1 || cboMateriaPrima.getSelectedIndex() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un producto y una materia prima.");
            return;
        }

        try {
            int cantidadUsada = Integer.parseInt(txtCantidadUsada.getText());

            // Producto seleccionado
            String productoSeleccionado = (String) cboProductos.getSelectedItem();
            int idProducto = Integer.parseInt(productoSeleccionado.split(" - ")[0]);
            Producto producto = listaProductos.stream()
                    .filter(p -> p.getIdProducto() == idProducto)
                    .findFirst()
                    .orElse(null);

            // Materia prima seleccionada
            String materiaSeleccionada = (String) cboMateriaPrima.getSelectedItem();
            int idMateria = Integer.parseInt(materiaSeleccionada.split(" - ")[0]);
            MateriaPrima materiaPrima = listaMateriasPrimas.stream()
                    .filter(m -> m.getIdMateriaPrima() == idMateria)
                    .findFirst()
                    .orElse(null);

            if (producto != null && materiaPrima != null) {
                DetalleDeProducto detalle = new DetalleDeProducto(producto, materiaPrima, cantidadUsada);
                listaDetalles.add(detalle);
                actualizarTablaDetalles();
                txtCantidadUsada.setText("");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa una cantidad válida.");
        }
    }//GEN-LAST:event_btnGuardarDetalleActionPerformed

    private void btnGuardarMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaPrimaActionPerformed
        String nombre = txtNombreMateriaPrima.getText();

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
            return;
        }

        MateriaPrima m = new MateriaPrima(idMateriaPrimaActual, nombre);
        listaMateriasPrimas.add(m);

        idMateriaPrimaActual++;
        lblMateriaPrimaID.setText(String.valueOf(idMateriaPrimaActual));
        txtNombreMateriaPrima.setText("");

        actualizarComboMateriasPrimas();
    }//GEN-LAST:event_btnGuardarMateriaPrimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio02().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDetalle;
    private javax.swing.JButton btnGuardarMateriaPrima;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JComboBox<String> cboMateriaPrima;
    private javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCantidadUsada;
    private javax.swing.JLabel lblCnatidadFabricada;
    private javax.swing.JLabel lblCostoFabricacion;
    private javax.swing.JLabel lblDetaleProducto;
    private javax.swing.JLabel lblIdMateriaPrima;
    private javax.swing.JLabel lblMateriaPrimaDetalle;
    private javax.swing.JLabel lblMateriaPrimaID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreMateriaPrima;
    private javax.swing.JLabel lblProductoDetalle;
    private javax.swing.JLabel lblProductoId;
    private javax.swing.JLabel lblRegistrarMateriaPrima;
    private javax.swing.JLabel lblRegistrarProducto;
    private javax.swing.JLabel lblidProducto;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidadFabricada;
    private javax.swing.JTextField txtCantidadUsada;
    private javax.swing.JTextField txtCostoFabricacion;
    private javax.swing.JTextField txtNombreMateriaPrima;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
